export const ActionTypes = {
    TOGGLE_MODAL: 'TOGGLE_MODAL',
    ADD_COURSE: 'ADD_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',
    FILTER_COURSES: 'FILTER_COURSES',
    CREATE_NEW_USER: 'CREATE_NEW_USER',
    LOGOUT: 'LOGOUT'
}